### PR TITLE
Fix for issue #16 with failure to match body when PUT request

### PR DESCRIPTION
**Pull request by xelnaga**

### CODE REVIEW

**Comment by johanhaleby** [comment]
This is great! Thanks a lot, put would you mind adding a test for PUT as well?

**Comment by xelnaga** [comment]
> This is great! Thanks a lot, put would you mind adding a test for PUT as well?

There is a test already added in this PR in body_test.clj for the PUT functionality.  Is there somewhere else that another should be created?

**Comment by johanhaleby** [comment]
Oh sorry, my bad! Thanks again!

**Comment by johanhaleby** [comment]
@xelnaga Tried to make a new release, but as always leiningen has some new problems with gpg.

```
Starting to release stub-http 0.2.12, enter sonatype password if prompted.
Already up to date.
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
gpg: no valid OpenPGP data found.
gpg: decrypt_message failed: Unknown system error
Could not decrypt credentials from /Users/johan/.lein/credentials.clj.gpg
gpg: no valid OpenPGP data found.
gpg: decrypt_message failed: Unknown system error

See `lein help gpg` for how to install gpg.
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
gpg: no valid OpenPGP data found.
gpg: decrypt_message failed: Unknown system error
Could not decrypt credentials from /Users/johan/.lein/credentials.clj.gpg
gpg: no valid OpenPGP data found.
gpg: decrypt_message failed: Unknown system error
```

I usually have to spend hours for every release since there's always a new error with leiningen and gpg. Do you have any clues? :)

**Pull request merged**
